# Generated by Django 5.0.6 on 2024-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days (max 20 days)')),
                ('description', models.TextField(max_length=2000)),
                ('annotation', models.TextField(max_length=100)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poster', models.ImageField(default='tour.jpg', upload_to='tours')),
            ],
        ),
    ]
