# Generated by Django 5.0.6 on 2024-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_reference',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
