# Generated by Django 5.0.6 on 2024-06-18 10:06

from django.db import migrations

def populate_reference_code(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')
    for reservation in Reservation.objects.all():
        reservation.reservation_reference = f'RES{reservation.reservation_number:06d}'
        reservation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_reservation_reference'),
    ]

    operations = [
        migrations.RunPython(populate_reference_code),
    ]
