# Generated by Django 5.0.6 on 2024-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20240618_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_reference',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
